label: dev-application
server:
  #port: 80
  servlet:
    context-path: /parent
spring:
  profiles:
    active: c3p0, rabbitmq
  jpa:
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true #日志中显示sql语句
#debug: true